# Generated by Django 4.1.2 on 2022-10-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
