# Generated by Django 4.1.2 on 2022-10-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms', models.ImageField(upload_to='slidering/')),
                ('cms_title', models.CharField(max_length=200, verbose_name='Title')),
                ('cms_text', models.TextField(max_length=200, verbose_name='Text')),
            ],
        ),
    ]
