# Generated by Django 4.1.2 on 2022-10-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsslider',
            name='cms',
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS'),
        ),
        migrations.AddField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(default=1, upload_to='sliderimg/'),
            preserve_default=False,
        ),
    ]
