# Generated by Django 4.1.2 on 2022-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_cmsslider_cms_cmsslider_cms_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_text',
            field=models.CharField(max_length=200, verbose_name='Text'),
        ),
    ]
